import './globals.css'
import Nav from './nav'
import "slick-carousel/slick/slick.css"; 
import "slick-carousel/slick/slick-theme.css";
import Footer from './Footer';

import { Inter, Dela_Gothic_One, Poppins } from 'next/font/google'
const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter',
})
const dela = Dela_Gothic_One({ 
  subsets: ['latin'], 
  weight: "400",
  variable: '--font-dela',
})
const poppins = Poppins({
  subsets: ['latin'],
  weight: ["400", "500", "600", "700", "800", "900"],
  variable: '--font-poppins',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${inter.variable} ${dela.variable} ${poppins.variable} font-poppins`}>
      <body>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  )
}
